Removed bootsrap section.
-  bootstrap: [AppComponent]
+  //bootstrap: [AppComponent]

its inclusion was causing the following error when running "ng test":

ERROR in app.component.spec.ts(44,3): error TS2345: Argument of type '{ declarations: (typeof DateComponent | typeof StandingsComponent | typeof Test2Component | typeo...' is not assignable to parameter of type 'TestModuleMetadata'.
  Object literal may only specify known properties, and 'bootstrap' does not exist in type 'TestModuleMetadata'.